version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
    container_name: pem-frontend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db
    container_name: pem-backend
  db:
    env_file: pg.env
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d/
    container_name: pem-db

networks:
  personal-expense-manager_default:
    driver: bridge
