version: '1'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=<user>
      - POSTGRES_PASSWORD=<password>
      - POSTGRES_DB=<database>
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d/